export interface Company {
  /**
   * EN: Unique identifier for the company
   * PT: Identificador único para a empresa
   */
  id: string;
  
  /**
   * EN: Company name
   * PT: Nome da empresa
   */
  name: string;
  
  /**
   * EN: Brazilian company registration number (CNPJ)
   * PT: Número de registro da empresa brasileira (CNPJ)
   */
  cnpj: string;
  
  /**
   * EN: Company street address
   * PT: Endereço da empresa
   */
  address?: string;
  
  /**
   * EN: City where the company is located
   * PT: Cidade onde a empresa está localizada
   */
  city?: string;
  
  /**
   * EN: State or province where the company is located
   * PT: Estado ou província onde a empresa está localizada
   */
  state?: string;
  
  /**
   * EN: Postal/ZIP code
   * PT: Código postal/CEP
   */
  zipCode?: string;
  
  /**
   * EN: Contact phone number
   * PT: Número de telefone para contato
   */
  phone?: string;
  
  /**
   * EN: Contact email address
   * PT: Endereço de email para contato
   */
  email?: string;
  
  /**
   * EN: Company website URL
   * PT: URL do site da empresa
   */
  website?: string;
  
  /**
   * EN: Brief description of the company
   * PT: Breve descrição da empresa
   */
  description?: string;
  
  /**
   * EN: URL or path to company logo image
   * PT: URL ou caminho para a imagem do logotipo da empresa
   */
  logo?: string;
  
  /**
   * EN: Flag indicating if the company is currently active
   * PT: Indicador se a empresa está atualmente ativa
   */
  active: boolean;
}

/**
 * Company Form Data Interface
 * 
 * EN: Interface for company data used in forms when creating or updating a company.
 * This interface mirrors the Company interface but omits the ID field which is
 * generated by the backend.
 * 
 * PT: Interface para dados de empresa usados em formulários ao criar ou atualizar uma empresa.
 * Esta interface espelha a interface Company, mas omite o campo ID que é
 * gerado pelo backend.
 */
export interface CompanyFormData {
  name: string;
  cnpj: string;
  address?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  phone?: string;
  email?: string;
  website?: string;
  description?: string;
  logo?: string;
  active: boolean;
}
