export interface Person {
  /**
   * EN: Unique identifier for the person
   * PT: Identificador único para a pessoa
   */
  id: string;
  
  /**
   * EN: Person's full name
   * PT: Nome completo da pessoa
   */
  name: string;
  
  /**
   * EN: Brazilian individual taxpayer registry identification (CPF)
   * PT: Cadastro de Pessoa Física (CPF)
   */
  cpf: string;
  
  /**
   * EN: Brazilian general registry identification (RG)
   * PT: Registro Geral (RG)
   */
  rg?: string;
  
  /**
   * EN: Person's date of birth in ISO format
   * PT: Data de nascimento da pessoa em formato ISO
   */
  birthDate?: string;
  
  /**
   * EN: Person's street address
   * PT: Endereço da pessoa
   */
  address?: string;
  
  /**
   * EN: City where the person lives
   * PT: Cidade onde a pessoa reside
   */
  city?: string;
  
  /**
   * EN: State or province where the person lives
   * PT: Estado ou província onde a pessoa reside
   */
  state?: string;
  
  /**
   * EN: Postal/ZIP code
   * PT: Código postal/CEP
   */
  zipCode?: string;
  
  /**
   * EN: Landline phone number
   * PT: Número de telefone fixo
   */
  phone?: string;
  
  /**
   * EN: Mobile phone number
   * PT: Número de telefone celular
   */
  mobilePhone?: string;
  
  /**
   * EN: Email address
   * PT: Endereço de email
   */
  email?: string;
  
  /**
   * EN: Person's profession or occupation
   * PT: Profissão ou ocupação da pessoa
   */
  profession?: string;
  
  /**
   * EN: Additional notes about the person
   * PT: Notas adicionais sobre a pessoa
   */
  notes?: string;
  
  /**
   * EN: Flag indicating if the person record is currently active
   * PT: Indicador se o registro da pessoa está atualmente ativo
   */
  active: boolean;
}

/**
 * Person Form Data Interface
 * 
 * EN: Interface for person data used in forms when creating or updating a person.
 * This interface mirrors the Person interface but omits the ID field which is
 * generated by the backend.
 * 
 * PT: Interface para dados de pessoa usados em formulários ao criar ou atualizar uma pessoa.
 * Esta interface espelha a interface Person, mas omite o campo ID que é
 * gerado pelo backend.
 */
export interface PersonFormData {
  name: string;
  cpf: string;
  rg?: string;
  birthDate?: string;
  address?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  phone?: string;
  mobilePhone?: string;
  email?: string;
  profession?: string;
  notes?: string;
  active: boolean;
}
